# Generated by Django 3.1.7 on 2021-02-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('main_image', models.URLField()),
                ('price', models.FloatField(max_length=10)),
                ('logos', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('C', 'Clothing'), ('A', 'Accessories'), ('G', 'Gear')], default='C', max_length=1)),
                ('featured', models.BooleanField(default=False)),
                ('soldout', models.BooleanField(default=False)),
            ],
        ),
    ]
