# Generated by Django 3.1.7 on 2021-02-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210226_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='designer',
            field=models.CharField(default='P. Rhogar', max_length=50),
            preserve_default=False,
        ),
    ]
